CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,

    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USERS_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('USER', 'ADMIN'))
);

CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;

CREATE TABLE REFRESH_TOKENS (
    TOKEN_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TOKEN_VALUE VARCHAR2(2000) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    REVOKED_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    REVOKED_AT TIMESTAMP,

    CONSTRAINT FK_REFRESH_TOKENS_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UK_REFRESH_TOKEN_VALUE UNIQUE (TOKEN_VALUE),
    CONSTRAINT CK_REFRESH_REVOKED_YN CHECK (REVOKED_YN IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_REFRESH_TOKENS START WITH 1 INCREMENT BY 1;

CREATE TABLE PLAYLISTS (
    PLAYLIST_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    DESCRIPTION CLOB,
    COVER_IMAGE_URL VARCHAR2(1000),
    PUBLIC_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
    LIKE_COUNT NUMBER DEFAULT 0 NOT NULL,
    COMMENT_COUNT NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,

    CONSTRAINT FK_PLAYLISTS_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT CK_PLAYLISTS_PUBLIC_YN CHECK (PUBLIC_YN IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_PLAYLISTS START WITH 1 INCREMENT BY 1;

CREATE TABLE PLAYLIST_TRACKS (
    PLAYLIST_TRACK_ID NUMBER PRIMARY KEY,
    PLAYLIST_ID NUMBER NOT NULL,
    SPOTIFY_TRACK_ID VARCHAR2(100) NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    ARTIST_NAME VARCHAR2(255) NOT NULL,
    ALBUM_NAME VARCHAR2(255),
    ALBUM_IMAGE_URL VARCHAR2(1000),
    SPOTIFY_URL VARCHAR2(1000) NOT NULL,
    PREVIEW_URL VARCHAR2(1000),
    DURATION_MS NUMBER,
    POSITION_NO NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,

    CONSTRAINT FK_PLAYLIST_TRACKS_PLAYLIST
        FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(PLAYLIST_ID)
);

CREATE SEQUENCE SEQ_PLAYLIST_TRACKS START WITH 1 INCREMENT BY 1;

CREATE TABLE COMMENTS (
    COMMENT_ID NUMBER PRIMARY KEY,
    PLAYLIST_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,

    CONSTRAINT FK_COMMENTS_PLAYLIST
        FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(PLAYLIST_ID),
    CONSTRAINT FK_COMMENTS_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE SEQ_COMMENTS START WITH 1 INCREMENT BY 1;

CREATE TABLE PLAYLIST_LIKES (
    LIKE_ID NUMBER PRIMARY KEY,
    PLAYLIST_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,

    CONSTRAINT FK_PLAYLIST_LIKES_PLAYLIST
        FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(PLAYLIST_ID),
    CONSTRAINT FK_PLAYLIST_LIKES_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UK_PLAYLIST_LIKES UNIQUE (PLAYLIST_ID, USER_ID)
);

CREATE SEQUENCE SEQ_PLAYLIST_LIKES START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_REFRESH_TOKENS_USER
ON REFRESH_TOKENS (USER_ID, REVOKED_YN, EXPIRES_AT);

CREATE INDEX IDX_PLAYLISTS_USER_ID
ON PLAYLISTS (USER_ID, CREATED_AT);

CREATE INDEX IDX_PLAYLISTS_PUBLIC_CREATED
ON PLAYLISTS (PUBLIC_YN, DELETED_AT, CREATED_AT);

CREATE INDEX IDX_PLAYLISTS_PUBLIC_VIEW
ON PLAYLISTS (PUBLIC_YN, DELETED_AT, VIEW_COUNT);

CREATE INDEX IDX_PLAYLISTS_PUBLIC_LIKE
ON PLAYLISTS (PUBLIC_YN, DELETED_AT, LIKE_COUNT);

CREATE INDEX IDX_TRACKS_PLAYLIST_POSITION
ON PLAYLIST_TRACKS (PLAYLIST_ID, DELETED_AT, POSITION_NO);

CREATE UNIQUE INDEX UK_PLAYLIST_TRACK_ACTIVE_POSITION
ON PLAYLIST_TRACKS (
    CASE WHEN DELETED_AT IS NULL THEN PLAYLIST_ID END,
    CASE WHEN DELETED_AT IS NULL THEN POSITION_NO END
);

CREATE INDEX IDX_TRACKS_SPOTIFY_ID
ON PLAYLIST_TRACKS (SPOTIFY_TRACK_ID);

CREATE INDEX IDX_COMMENTS_PLAYLIST_CREATED
ON COMMENTS (PLAYLIST_ID, DELETED_AT, CREATED_AT);

CREATE INDEX IDX_COMMENTS_USER_CREATED
ON COMMENTS (USER_ID, DELETED_AT, CREATED_AT, COMMENT_ID);

CREATE INDEX IDX_LIKES_PLAYLIST
ON PLAYLIST_LIKES (PLAYLIST_ID, DELETED_AT);

CREATE INDEX IDX_LIKES_USER
ON PLAYLIST_LIKES (USER_ID, DELETED_AT, CREATED_AT, LIKE_ID);
